### ISSUE TITLE
Do not log the connection

### ISSUE THREAD

**Issue by IceflowRE** [thoj/go-ircevent#105]
A library shouldnt log something or at least provide an option to turn it off.
I mean this line: https://github.com/thoj/go-ircevent/blob/master/irc.go#L468

**Comment by emacski** [comment]
@IceflowRE you will notice that the `Log` field is exported in the `Connection` struct, so you do have some control over how this library logs when implementing.

Quick and dirty example of "turning off" logging:
```
package main

import (
    "io/ioutil"

    irc "github.com/thoj/go-ircevent"
)

func main() {
    conn := irc.IRC("mynick", "myuser")
    conn.Log.SetOutput(ioutil.Discard)
}
```
