### ISSUE TITLE
Problems with IRC colors and formatting

### ISSUE THREAD

**Issue by IceflowRE** [thoj/go-ircevent#106]
If someone sends a color or a formatting attribute, the callback gets weird a string back.
1. It does not contain the text only
2. It contains **parts** of the formatting attributes
3. Theres no chance to get the **real** original bytes of the message

Maybe exclude those formatting attributes from the message or give another option to get the message as byte slice.

**Comment by thoj** [comment]
I'm pretty sure this was at-least partially fixed.
