### ISSUE TITLE
nil pointer dereference in irc.go:81

### ISSUE THREAD

**Issue by oddlid** [thoj/go-ircevent#110]
When using this lib to connect to OFTC, it's all working fine, but when I connect to a local ZNC instance, I get a nil pointer dereference from irc.go at line 81. 
It seems in line 80 that parseToEvent(msg) is returning nil, and then on the next line the returned reference is used before any errors are checked.
There is probably something strange coming back from ZNC which causes this, but it's hard to debug as the program crashes with panic due to this.

**Comment by thoj** [comment]
Turn on debugging irc.Debug := true and se if the message is printed out.

**Comment by oddlid** [comment]
I did, and found my own errors. I connected to the wrong port which was the web interface. It's all working nicely for me now, thanks :)
Still, I think it would be good practice to check the error before trying to use a returned reference which might be nil, to avoid crashes.
And thanks for the quick response :)
