### ISSUE TITLE
is there an onNewUserHasJoinedChannel event?

### ISSUE THREAD

**Issue by bnfinet** [thoj/go-ircevent#118]
Forgive my naivete, is there a way to construct a callback for being notified when a new user joins a channel?

I'd like to notify new users to "please use a pastebin" just after they `/join` the irc channel for our project.  I have a bot running there based upon [go-chat-bot/bot](https://github.com/go-chat-bot/bot/blob/master/irc/irc.go) which relies upon this library.

Thanks much!

**Comment by dax-dev** [comment]
Some servers send a JOIN message to the channel when a member joins, so you could add a callback for that, and check to see if the source is different from the client
