### ISSUE TITLE
Not compatible with HexChat

### ISSUE THREAD

**Issue by Dontmindmes** [thoj/go-ircevent#125]
Hey i noticed that the bot can not print out to hex chat for some reason?

**Comment by IceflowRE** [comment]
What does this mean?
This library uses only the IRC protocol, it cannot interact in another way with HexChat. (afaik)
And messages send with this library are readable by HexChat.

**Comment by Dontmindmes** [comment]
When I attempt to execute commands from the hexchat client the command just executed but bot does not print response

**Comment by IceflowRE** [comment]
Examples would be nice.

**Comment by Dontmindmes** [comment]
On freenodeirc the bot is able to send text and it's visible
But when I use hexchat I don't see the chat, it doesn't print

**Comment by belak** [comment]
Can you provide some sample code?

**Comment by Dontmindmes** [comment]
Sample Code?

> irccon.Privmsgf(channel, "Visit paramaters are in correct!")

thats the code i use for printing, but its only visible in freenode and not hexchat

**Comment by belak** [comment]
How are you viewing the messages? Are you using a different IRC client?

**Comment by Dontmindmes** [comment]
I am viewing the messages using freenodes web irc client 
and using hexchat another irc client but downloaded

**Comment by Dontmindmes** [comment]
https://webchat.freenode.net

**Comment by Dontmindmes** [comment]
also hybrid irc is being used

**Comment by IceflowRE** [comment]
You should know the difference between
```golang
// Send (private) message to a target (channel or nickname).
// RFC 1459 details: https://tools.ietf.org/html/rfc1459#section-4.4.1
func (irc *Connection) Privmsg(target, message string) {
	irc.pwrite <- fmt.Sprintf("PRIVMSG %s :%s\r\n", target, message)
}

// Send formated string to specified target (channel or nickname).
func (irc *Connection) Privmsgf(target, format string, a ...interface{}) {
	irc.Privmsg(target, fmt.Sprintf(format, a...))
}
````
those two functions.

**Comment by IceflowRE** [comment]
No problems so far
```golang
package main

import (
	"crypto/tls"
	"fmt"
	"os"
	"os/signal"
	"syscall"

	ircE "github.com/thoj/go-ircevent"
)

func main() {
	iConn := ircE.IRC("ice-test", "ice-test")
	iConn.UseTLS = true
	iConn.TLSConfig = &tls.Config{InsecureSkipVerify: true}
	iConn.AddCallback(
		"001",
		func(e *ircE.Event) {
			iConn.Join("#ice-test")
			iConn.Privmsg("#ice-test", "Visit paramaters are in correct!")
		},
	)

	err := iConn.Connect("irc.freenode.net:7000")
	if err != nil {
		fmt.Println(err)
		return
	}

	sc := make(chan os.Signal, 1)
	signal.Notify(sc, syscall.SIGINT, syscall.SIGTERM, os.Interrupt, os.Kill)
	select {
	case <-sc:
	}
	iConn.Quit()
}
```

**Comment by IceflowRE** [comment]
No problems so far
```golang
package main

import (
	"crypto/tls"
	"fmt"
	"os"
	"os/signal"
	"syscall"

	ircE "github.com/thoj/go-ircevent"
)

func main() {
	iConn := ircE.IRC("ice-test", "ice-test")
	iConn.UseTLS = true
	iConn.TLSConfig = &tls.Config{InsecureSkipVerify: true}
	iConn.AddCallback(
		"001",
		func(e *ircE.Event) {
			iConn.Join("#ice-test")
			iConn.Privmsg("#ice-test", "Visit paramaters are in correct!")
			iConn.Privmsgf("#ice-test", "Visit paramaters are in correct!")
		},
	)

	err := iConn.Connect("irc.freenode.net:7000")
	if err != nil {
		fmt.Println(err)
		return
	}

	sc := make(chan os.Signal, 1)
	signal.Notify(sc, syscall.SIGINT, syscall.SIGTERM, os.Interrupt, os.Kill)
	select {
	case <-sc:
	}
	iConn.Quit()
}
```

**Comment by Dontmindmes** [comment]
This is the code im using, but it only prints when im using freenode server and not hybrid

`	irccon := irc.IRC(name, "Agent")
	irccon.VerboseCallbackHandler = false
	irccon.Debug = true
	irccon.UseTLS = false
	irccon.TLSConfig = &tls.Config{InsecureSkipVerify: false}
	irccon.Password = "Test123"

	irccon.AddCallback("001", func(e *irc.Event) { irccon.Join(channel) })
	irccon.AddCallback("366", func(e *irc.Event) {})

	// Backup server added, if fails to connect to first one it will connect to second server
	for {
		err := irccon.Connect(serverssl)
		if err != nil {
			fmt.Printf("Err %s", err)
			err := irccon.Connect(serverssl2)
			if err != nil {
				// Room to add a 3rd backup server here
				return
			}
		}`

**Comment by IceflowRE** [comment]
Sry to bother you, but can you provide an working example?
The code above is not even a complete code snippet.

**Comment by Dontmindmes** [comment]
idk how to provide an example xD My code is 1000+ lines xD but that code is the conenction code and 
im not using

> ```sc := make(chan os.Signal, 1)
	signal.Notify(sc, syscall.SIGINT, syscall.SIGTERM, os.Interrupt, os.Kill)
	select {
	case <-sc:
	}
	iConn.Quit()````

and im using this
https://gyazo.com/b3fdb18973e1be67bf0b63ecae033f7c

**Comment by thoj** [comment]
Make a minimal example that doesn't work like expected.

But I think this has more to do with hexchat. Have you checked that the bot is not on a ignore list? If it's private messages you are sending that hexchat is set up to accept and open a privmsg window?

**Comment by Dontmindmes** [comment]
No it works, when I use hexchat to connect to freenode servers the bot works it can send messages to the chat

But when I use hexchat to connect to my private hybrid IRC it dosent send chat

**Comment by IceflowRE** [comment]
Tested it now with Hybrid IRC: https://kiwiirc.hybridirc.com/

I used same code i already posted above: https://github.com/thoj/go-ircevent/issues/125#issuecomment-499483451

Had no problems.
Please have in mind that `You must wait 10 seconds after joining to send to channel (+d)`, probably you run into that issue, but in summary this is no problem with this library.
