### ISSUE TITLE
How can I make a connection using proxy?

### ISSUE THREAD

**Issue by avdb13** [thoj/go-ircevent#136]
`ircobj.Connect()` only accepts a string parameter. I want to connect my bot to an IRC server hosted on the Tor network which requires me to use the default socks5 proxy which is active on on `localhost:9050`.
I found this useful example on the internet on how to use a proxy in Go: https://play.golang.org/p/l0iLtkD1DV

**Comment by thoj** [comment]
Socks5 is not supported. Pull requests welcome.You can probably use sockscap to force it. 24. mai 2021 17:43 skrev avdb ***@***.***>:
ircobj.Connect() only accepts a string parameter. I want to connect my bot to an IRC server hosted on the Tor network which requires me to use the default socks5 proxy which is active on on localhost:9050.
I found this useful example on the internet on how to use a proxy in Go: https://play.golang.org/p/l0iLtkD1DV
