### ISSUE TITLE
Calling Quit() closes channel but doesn't send QUIT to server

### ISSUE THREAD

**Issue by sangelone** [thoj/go-ircevent#32]
**Description**: neither Quit() nor Disconnect() will make a bot quit IRC. The channel still gets closed, however, so it crashes on the next message received by the connection (i.e. PING or PRIVMSG).

**The error**: `panic: runtime error: send on closed channel`

**To reproduce**: update to the latest code on master. Have a bot join a channel on a server and then call Quit(). See that it does not quit the server. Send it a message or ping it and see that it crashes.

**Comment by Strubbl** [comment]
I am calling Quit() and directly after that Disconnect() on my IRC connection. The quit works fine, but the disconnect is somehow hanging and does not come to the end of the method - even after 5 minutes it still did not end. Am i doing something wrong?
