### ISSUE TITLE
too many open files

### ISSUE THREAD

**Issue by peternavr** [thoj/go-ircevent#37]
After enough disconnects I eventually get "too many open files" errors.

**Comment by adraenwan** [comment]
This is still an issue for me:
When my bot run for a long time, invariably, it ends by charshing (possess still running, but will never reconnect to server).

from that moment on, it logs constantly:

```
Error while reconnecting: dial tcp: lookup barjavel.freenode.net: too many open files
Error, disconnected: dial tcp: lookup barjavel.freenode.net: lookup barjavel.freenode.net: too many open files
```

about 25 times / sec (meaning a ~40ms period).
