### ISSUE TITLE
Grab Channel Name Inside Event?

### ISSUE THREAD

**Issue by hspak** [thoj/go-ircevent#55]
Is it possible to associate an event to a particular channel? I've looked at the structs and haven't found anything useful.

For example, if I have a callback for PRIVMSG, is it possible to from what channel it came from?

**Comment by fabioxgn** [comment]
The channel is the first argument in the `Event` struct:

```Go
func onPRIVMSG(e *irc.Event) {
	fmt.Println(e.Arguments[0]);
} ```

This will print the channel.

**Comment by hspak** [comment]
Thanks!
