### ISSUE TITLE
Msg slice out of range

### ISSUE THREAD

**Issue by hspak** [thoj/go-ircevent#57]
I got a runtime panic because of [these](https://github.com/thoj/go-ircevent/blob/master/irc_callback.go#L83-L85) lines.

I'm not sure what message caused it, but here's a stack trace of it. It's from my [pulled](https://github.com/thoj/go-ircevent/compare/master...hspak:master) version, but I've only added a delay between reconnects.

```
panic: runtime error: slice bounds out of range

goroutine 32 [running]:
runtime.panic(0x744cc0, 0x983dcf)
	/usr/lib/golang/src/pkg/runtime/panic.c:279 +0xf5
github.com/hspak/go-ircevent.(*Connection).RunCallbacks(0xc208278120, 0xc2080f8480)
	/home/hsp/code/gocode/src/github.com/hspak/go-ircevent/irc_callback.go:84 +0xb44
github.com/hspak/go-ircevent.(*Connection).readLoop(0xc208278120)
	/home/hsp/code/gocode/src/github.com/hspak/go-ircevent/irc.go:104 +0x93d
created by github.com/hspak/go-ircevent.(*Connection).Connect
	/home/hsp/code/gocode/src/github.com/hspak/go-ircevent/irc.go:381 +0xae1
```

**Comment by thoj** [comment]
I guess this could happen if msg is "\x01"? Change the check about to len(msg) > 2 would fix this. Probably.

**Comment by thoj** [comment]
087ae892d056f3699db20764b67d785a6980266f fixes this.
