### ISSUE TITLE
Can't use GetName

### ISSUE THREAD

**Issue by witheld9** [thoj/go-ircevent#59]
Attempting to use GetName results in bot.go:46: undefined: irc.GetName

I also can't find any other way to get my current nickname

**Comment by thoj** [comment]
irc.GetNick()

**Comment by witheld9** [comment]
./madbot.go:69: undefined: irc.GetNick

That original was me copying the wrong thing from when I was just pretty much acting randomly out of sleep deprivation trying to make this work. GetNick is not working, and I've got a whole bot implemented otherwise with multiple network support and all that jazz so the library itself is working

**Comment by thoj** [comment]
Can i see the code in question? GetNick() is a function:

  // Determine nick currently used with the connection.
  func (irc *Connection) GetNick() string {
	  return irc.nickcurrent
  }

**Comment by witheld9** [comment]
https://gist.github.com/witheld9/a85dc5cfcc40c042d8bb here's an example where I try to use it in the function join

**Comment by darkliquid** [comment]
You're not using it correctly. GetNick is a method on the Connection object, but you're trying to call it as a method of the irc package, and that doesn't exist.

It looks like what you want to do is call either:
```go
func join(event *irc.Event) {
nicktest := event.Connection.GetNick()
}
```

or

```go
func join(event *irc.Event) {
nicktest := event.Nick
}
```

depending on what it is you actually want to achieve (the first, getting the nick of the bot, the second getting the nick of the instigator of the event)

**Comment by witheld9** [comment]
That was it
