### ISSUE TITLE
Potential panic on unterminated CTCP messages.

### ISSUE THREAD

**Issue by alaska** [thoj/go-ircevent#61]
I had a bot I wrote using this lib crash the other day with a `slice bounds out of range` error at irc_callback.go: 84.  Sadly, I didn't have verbosity on at the time, so I wasn't able to see the message that generated it, but I suspect it was something that started with `\0x01` and did contain another `\0x01`.  This would mean that the slice would evaluate to 
```go
msg = msg[1:0]
```
Which panics.  I'll update the bug if I see it again, but it might be worth adding a check.

**Comment by thoj** [comment]
Thanks :+1:
