### ISSUE TITLE
Separating queries and channel messages

### ISSUE THREAD

**Issue by Moter8** [thoj/go-ircevent#63]
Hey, I love the library and already wrote a small bot with it. A problem I face though is that I can't see from where the privmsg comes from.

It would be nice if I could see if the message came from a channel or from a query.

I found that I could see the channel via e.Raw but there should be an easier way imo?

**Comment by Moter8** [comment]
Got it working analyzing the raw messages:

e.Raw Private Query: `:Moter8!Moter8@user/Moter8 PRIVMSG MoterBot :test`
e.Raw Channel Query: `:Moter8!Moter8@user/Moter8 PRIVMSG #mychannel :test`

```go
con.AddCallback("PRIVMSG", func(e *irc.Event) {
  channel := strings.Split(e.Raw, " ")[2] // either GetNick() or #mychannel

  if channel == con.GetNick() {
    channel = strings.Split(e.Raw[1:], "!")[0]  // Starting from the [1]st char, split at "!", store as string
    fmt.Println("Private Query detected")
    return // if it shouldn't answer on private query
  }
  // do things with the channel query
}
```

**Comment by lidel** [comment]
Thanks @Moter8, I was about to look for this functionality, now I don't need too :+1:
