### ISSUE TITLE
Getting Information about Users/Ops in a Channel

### ISSUE THREAD

**Issue by Moter8** [thoj/go-ircevent#64]
Hey there, how can I achieve this with the library?

Some commands/callbacks should only be executed if it's executed by operators/halfops etc.

**Comment by darkliquid** [comment]
I did something to track user privileges across channels in some old bot code I wrote for https://github.com/darkliquid/leader1 

The state tracking stuff in **state** and the builtin stuff in **bots** are things to look at for some examples, however poor they may be :)

**Comment by thoj** [comment]
You need to track channel state to do this properly. There is currently no channel/nicklist tracking code implemented. Patches very welcome!

**Comment by thoj** [comment]
See #79
