### ISSUE TITLE
Loop() is not goroutine safe

### ISSUE THREAD

**Issue by Joshua-Anderson** [thoj/go-ircevent#67]
Package tests run a second connection with `go irccon.Loop()`, like [here](https://github.com/thoj/go-ircevent/blob/master/irc_test.go#L234).

I've been using this code in my own libraries with `-race` and discovered a bunch of race conditions, such as `github.com/thoj/go-ircevent.(*Connection).RunCallbacks()` and `github.com/thoj/go-ircevent.(*Connection).AddCallback()`

These issues seem like they could easily be solved by adding some mutexes around unsafe operations like callback map access. I may have the time to fix this in the next few weeks, but I'm not sure.

**Comment by thoj** [comment]
Work in progress. Latest change will fix some of the issues. See da78ed515c0f0833e7a92c7cc52898176198e2c1

**Comment by thoj** [comment]
Most races has been fixed.
