### ISSUE TITLE
irb bot example giving me one error

### ISSUE THREAD

**Issue by ChrisFernandez** [thoj/go-ircevent#71]
new to golang but following this example to create a bot for fun,
https://waterpigs.co.uk/articles/a-simple-go-irc-bot/
but getting this msg below
line 25: cannot convert e.Message (type func() string) to type string
since I am copying and pasting I wonder if a new version of golang have made somechanges that that example does not work anymore?
is trying to echo the eMessage that is a msg sent to the irc channel... 
im sure this is very simple solution just trying to understand whats wrong.

thanks

**Comment by lidel** [comment]
`Message` is a function. Try `e.Message()` instead of `e.Message`.

**Comment by ChrisFernandez** [comment]
yap you got it! thanks.
Im also trying to see if a PRVMSG contains http or https if it does sent it to a func that will get info about the site..
if e.Message().Contains("http", "https") {
                        resolveUrl(e.Message())
                       /* do something with response from the resolveUrl func */
}

but I get this:

eMessage().Contains undefined (type string has no field or method Contains)

sorry for the stupid questions, trying to learn golang building a bot for my irc channel.
I searched for how to know if a string contains some words and found .contains and .containsAny

**Comment by ChrisFernandez** [comment]
ok I think I figure out.. I got way to used to objects in the last 15 years... there no objects in Golang so I can't just do.go things. so Contains is a function and thats why the issue..  so not sure Contains is going to work out for me.

**Comment by lidel** [comment]
Correct, `strings.Contains(str, subStr)` is the way to go :+1: 

For more advanced checks you can use [regular expressions](https://gobyexample.com/regular-expressions).

PS.  https://gobyexample.com is a good resource with a lot of examples for usual operations.

**Comment by ChrisFernandez** [comment]
thanks for the links! I may actually end up using regex. thanks.
one last question I promess!! :) 
Im trying to sent the e.Message to the funtion where Im going to get the URL info:
con.Privmsg(roomName, resolveUrl(eMessage()))
but i get:
/gobot.go:41: resolveUrl(eMessage()) used as value
so I can't pass arguments to a function in that way? not sure whats the issue.

**Comment by lidel** [comment]
The ` used as value` error suggests that you did not define the return type of `resolveUrl`:

Function definition should look like this (takes string and returns a string): 
```go
func resolveUrl(message string) string { 
```

----

If you have any further issues, we really should move this somewhere else :-) 
Feel free to [email me](https://mailnull.com/cgi-bin/webmail?au=5f94bec2340bd2445448e75d11cc5a66).

**Comment by ChrisFernandez** [comment]
yes that worked!! thanks so much for your help. I'm going to bed but if tomorrow I step into more new issues I will email you.
Thanks!
