### ISSUE TITLE
limit in output to the channel?

### ISSUE THREAD

**Issue by ChrisFernandez** [thoj/go-ircevent#72]
I have a piece of code that grabs a mediawiki site, it does it well because it comes out on stdout, but when sending to go-ircevent only first line comes out on the irc channel... anyway to make this 3-4 lines instead?

**Comment by darkliquid** [comment]
IRC doesn't allow for CR/LF in messages, so the only way you can achieve multiline messages is to split the message on CR/LF and send a separate message for each line.

**Comment by ChrisFernandez** [comment]
yeah I remember that, so was able to just use a html parser and just get the first <p></p> paragraph in one line and that's working great with out having to spam the channel. thanks. I'm trying to make it work over TOR now, almost done.
