### ISSUE TITLE
Reconnect regression on ping timeout

### ISSUE THREAD

**Issue by lidel** [thoj/go-ircevent#73]
Just noticed that since I've rebuilt my bot with https://github.com/thoj/go-ircevent/commit/da78ed515c0f0833e7a92c7cc52898176198e2c1 reconnect on ping timeout stopped working:

```
2016/03/11 05:50:38 <-- :meowkov!~meowkov@foo.bar QUIT :Ping timeout: 250 seconds
2016/03/11 05:54:29 --> PING 1457675669498722486
2016/03/11 05:54:29 Error, disconnected: write tcp 172.17.0.2:49177->193.10.255.100:7000: write: broken pipe
```

I suspect fix from   #69 stopped working when https://github.com/thoj/go-ircevent/commit/da78ed515c0f0833e7a92c7cc52898176198e2c1 got introduced. 

Can anyone else replicate this behaviour?

**Comment by thoj** [comment]
I'll try to replicate this

**Comment by prologic** [comment]
Try with most recent master after #9 landed
