### ISSUE TITLE
Doesn't reconnect/disconnect 

### ISSUE THREAD

**Issue by ugjka** [thoj/go-ircevent#85]
If I kill the connection nothing happens (apart from PING beinng sent). If I do .Disconnect() nothing happens same with Reconnect()
I'm still learning go so I don't understand what is happening

**Comment by thoj** [comment]
If you show me your code I can help :-)
On Nov 2, 2016 19:09, ugjka <notifications@github.com> wrote:If I kill the connection nothing happens (apart from PING beinng sent). If I do .Disconnect() nothing happens same with Reconnect()
I'm still learning go so I don't understand what is happening

**Comment by ugjka** [comment]
Example: https://gist.github.com/36258b7a8555d173f3c7d76dd2b7bedd

go version go1.7.3 linux/amd64

**Comment by thoj** [comment]
You should check out the example here: 
https://github.com/thoj/go-ircevent/blob/master/irc_test.go#L258

you need to call irc.Loop() somewhere.

**Comment by ugjka** [comment]
Ok thanks, I should have thought of reading the tests. :)
