### ISSUE TITLE
Add reply function

### ISSUE THREAD

**Issue by handicraftsman** [thoj/go-ircevent#89]
Add `*irc.Event.Reply(msg string)`

**Comment by thoj** [comment]
Can you explain a bit more? What exactly do you need?

**Comment by handicraftsman** [comment]
@thoj, it replies to `*irc.Event.Arguments[0]`.

**Comment by belak** [comment]
I assume it would be similar to this: https://github.com/belak/go-seabird/blob/master/bot.go#L128

**Comment by handicraftsman** [comment]
@belak, i saw this in Cinch (ruby) before. But it looks same.
