### ISSUE TITLE
crash: maybe has race condition

### ISSUE THREAD

**Issue by kitech** [thoj/go-ircevent#93]
my usage:
     conn:= irc.IRC(); conn.Connect(...); 
then some commands. but i not using conn.Loop(), is that the problem?

readLoop: 

#0 0x00000000004b95d2 in crypto/tls.(*Conn).SetReadDeadline (c=0x0, t=..., ~r1=...)
at /usr/lib/go/src/crypto/tls/conn.go:122
#1 0x000000000046985b in github.com/thoj/go-ircevent.(Connection).readLoop (irc=0xc420352840)
at /golib/src/github.com/thoj/go-ircevent/irc.go:65
#2 0x0000000000464b11 in runtime.goexit () at /usr/lib/go/src/runtime/asm_amd64.s:2086
#3 0x000000c420352840 in ?? ()
#4 0x0000000000000000 in ?? ()

writeLoop:
#0  syscall.Syscall () at /usr/lib/go/src/syscall/asm_linux_amd64.s:27
#1  0x00000000005354f5 in syscall.write (fd=10, p=..., n=119, err=...)
    at /usr/lib/go/src/syscall/zsyscall_linux_amd64.go:1064
#2  0x00000000005346c9 in syscall.Write (fd=10, p=..., n=13, err=...) at /usr/lib/go/src/syscall/syscall_unix.go:180
#3  0x00000000004f8e7a in net.(*netFD).Write (fd=0xc4200edf80, p=..., nn=0, err=...) at /usr/lib/go/src/net/fd_unix.go:321
#4  0x0000000000503770 in net.(*conn).Write (c=0xc420074078, b=..., ~r1=0, ~r2=...) at /usr/lib/go/src/net/net.go:185
#5  0x00000000004c69c7 in crypto/tls.(*Conn).write (c=0xc42006f180, data=..., ~r1=842350677249, ~r2=...)
    at /usr/lib/go/src/crypto/tls/conn.go:819
#6  0x00000000004c6e63 in crypto/tls.(*Conn).writeRecordLocked (c=0xc42006f180, typ=23 '\027', data=..., ~r2=0, ~r3=...)
    at /usr/lib/go/src/crypto/tls/conn.go:895
#7  0x00000000004c7edb in crypto/tls.(*Conn).Write (c=0xc42006f180, b=..., ~r1=0, ~r2=...)
    at /usr/lib/go/src/crypto/tls/conn.go:1047
#8  0x000000000047141b in github.com/thoj/go-ircevent.(*Connection).writeLoop (irc=0xc4200f8000)
    at /golib/src/github.com/thoj/go-ircevent/irc.go:145
#9  0x000000000046b901 in runtime.goexit () at /usr/lib/go/src/runtime/asm_amd64.s:2086
#10 0x000000c4200f8000 in ?? ()
#11 0x0000000000000000 in ?? ()

**Comment by prologic** [comment]
Try after #9 landed; I may have fixed this :D
